@startuml
frame "Graph" {
  HTTP - [First Component]
  [Another Component]
}

frame "Surface" {
  [Table]->  [Surface Dialog]
}


database "storage" {
  [primitiveStorage]
  [graphStorage]
}

package "multivariate-polynomial" {
  [Monomial]<-  [Polynomial]
  [Polynomial]<-[Ideal]
}

package "Mi Librería" {
  [Shader] as shader
}

package "Aplicación" {
  [Graph] as graph
  [Surface] as surface
}

shader --> graph
shader --> surface

[Surface Dialog] -> [Polynomial]
[Surface Dialog] -> [Ideal]
[Surface Dialog] -> [primitiveStorage]
@enduml